# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = C:\Develop\CMake\bin\cmake.exe

# The command to remove a file.
RM = C:\Develop\CMake\bin\cmake.exe -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = D:\Dropbox\Work\biu\opensource\cmd_line

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = D:\Dropbox\Work\biu\opensource\cmd_line

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	C:\Develop\CMake\bin\cmake.exe -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	C:\Develop\CMake\bin\cmake.exe -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	C:\Develop\CMake\bin\cmake-gui.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	C:\Develop\CMake\bin\cmake.exe -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	C:\Develop\CMake\bin\cmake.exe -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	C:\Develop\CMake\bin\cmake.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start D:\Dropbox\Work\biu\opensource\cmd_line\CMakeFiles D:\Dropbox\Work\biu\opensource\cmd_line\CMakeFiles\progress.marks
	$(MAKE) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start D:\Dropbox\Work\biu\opensource\cmd_line\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cmd_line

# Build rule for target.
cmd_line: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 cmd_line
.PHONY : cmd_line

# fast build rule for target.
cmd_line/fast:
	$(MAKE) -f CMakeFiles\cmd_line.dir\build.make CMakeFiles/cmd_line.dir/build
.PHONY : cmd_line/fast

#=============================================================================
# Target rules for targets named tester

# Build rule for target.
tester: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 tester
.PHONY : tester

# fast build rule for target.
tester/fast:
	$(MAKE) -f CMakeFiles\tester.dir\build.make CMakeFiles/tester.dir/build
.PHONY : tester/fast

src/cmd_line.obj: src/cmd_line.cpp.obj
.PHONY : src/cmd_line.obj

# target to build an object file
src/cmd_line.cpp.obj:
	$(MAKE) -f CMakeFiles\cmd_line.dir\build.make CMakeFiles/cmd_line.dir/src/cmd_line.cpp.obj
.PHONY : src/cmd_line.cpp.obj

src/cmd_line.i: src/cmd_line.cpp.i
.PHONY : src/cmd_line.i

# target to preprocess a source file
src/cmd_line.cpp.i:
	$(MAKE) -f CMakeFiles\cmd_line.dir\build.make CMakeFiles/cmd_line.dir/src/cmd_line.cpp.i
.PHONY : src/cmd_line.cpp.i

src/cmd_line.s: src/cmd_line.cpp.s
.PHONY : src/cmd_line.s

# target to generate assembly for a file
src/cmd_line.cpp.s:
	$(MAKE) -f CMakeFiles\cmd_line.dir\build.make CMakeFiles/cmd_line.dir/src/cmd_line.cpp.s
.PHONY : src/cmd_line.cpp.s

src/tester.obj: src/tester.cpp.obj
.PHONY : src/tester.obj

# target to build an object file
src/tester.cpp.obj:
	$(MAKE) -f CMakeFiles\tester.dir\build.make CMakeFiles/tester.dir/src/tester.cpp.obj
.PHONY : src/tester.cpp.obj

src/tester.i: src/tester.cpp.i
.PHONY : src/tester.i

# target to preprocess a source file
src/tester.cpp.i:
	$(MAKE) -f CMakeFiles\tester.dir\build.make CMakeFiles/tester.dir/src/tester.cpp.i
.PHONY : src/tester.cpp.i

src/tester.s: src/tester.cpp.s
.PHONY : src/tester.s

# target to generate assembly for a file
src/tester.cpp.s:
	$(MAKE) -f CMakeFiles\tester.dir\build.make CMakeFiles/tester.dir/src/tester.cpp.s
.PHONY : src/tester.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... tester
	@echo ... install/local
	@echo ... install/strip
	@echo ... edit_cache
	@echo ... install
	@echo ... rebuild_cache
	@echo ... list_install_components
	@echo ... cmd_line
	@echo ... src/cmd_line.obj
	@echo ... src/cmd_line.i
	@echo ... src/cmd_line.s
	@echo ... src/tester.obj
	@echo ... src/tester.i
	@echo ... src/tester.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

